// src/lib/surfaceModGenerator.ts
import type { SurfaceMod } from '../types/surfaceModTypes'

export interface ModFileEntry {
  path: string
  text?: string
  cacheKey?: string
  isPlaceholder?: boolean
}

/**
 * Generates the raw text content for a Surface Mod package.
 * Returns a dictionary of filename -> content strings.
 */
export function generateSurfaceModFiles(mod: SurfaceMod): Record<string, string> {
  const files: Record<string, string> = {};

  // 1. Generate the standard Engine Manifest (.meta)
  const metaContent = [
    `GUID:${mod.modGuid}`,
    `Type:401`, 
    `UpdatedToGameVersion:17287`,
    `ModName:${mod.displayName || mod.internalName}`,
    `Enabled:False`,
    `IsSystemMod:False`,
    `CreationTime:0`,
    `LastEditTime:0`,
    `LastUploadTime:0`,
    `IsFromWorkshop:False`,
    `PublishedFileId:0`,
    `CreatorId:${mod.creatorId || 'StudioCreator'}`,
    `WorkshopDescription:Custom surface material generated by Paralives Mod Studio.`
  ].join('\r\n') + '\r\n';

  files[`${mod.internalName}.mod.meta`] = metaContent;

  // 2. Generate the Surface Properties Configuration
  // This maps the UI values directly into the proprietary format Paralives reads for walls/floors
  const surfaceContent = [
    `#SurfaceModSettings`,
    `InternalName:${mod.internalName}`,
    `DisplayName:${mod.displayName}`,
    `TilingX:${mod.tilingX}`,
    `TilingY:${mod.tilingY}`,
    `Smoothness:${mod.smoothnessValue}`,
    `Metallic:${mod.metallicValue}`,
    `Emissive:${mod.emissiveStrength}`,
    `AmbientOcclusion:${mod.ambientOcclusionStrength}`,
    `ColorZoneCount:${mod.colorZoneCount}`,
    `IsWallOrFloor:${mod.isWallOrFloor ? 'True' : 'False'}`,
    `WallYStretching:${mod.wallYStretching ? 'True' : 'False'}`,
    `SwatchCount:${mod.swatches.length}`
  ].join('\r\n') + '\r\n';

  // We place this inside the Settings/ folder of the zip archive
  files[`Settings/${mod.internalName}.surface`] = surfaceContent;

  return files;
}

export const filenameStem = (internalName: string) => internalName;